prometheus:
  service:
    type: NodePort
    nodePort: 30090  
  
  prometheusSpec:
    # Scrape configuration for the remote cluster
    additionalScrapeConfigs:
      - job_name: 'opencost-member-cluster'
        static_configs:
          - targets: ['10.3.2.163:30093'] 
        honor_labels: true
        scrape_interval: 15s
      - job_name: 'opencost-member2-cluster'
        static_configs:
          - targets: ['10.3.1.33:30093'] 
        honor_labels: true
        scrape_interval: 15s