prometheus:
  service:
    type: NodePort
    nodePort: 30090  
  
  prometheusSpec:
    # Scrape configuration for the remote cluster
    additionalScrapeConfigs:
      - job_name: 'opencost-member-cluster'
        static_configs:
          # O Prometheus vai buscar os dados à porta correta do OpenCost!
          - targets: ['10.3.2.163:30093'] #Todo: Atualizar para  o novo IP 10.3.2.164
        honor_labels: true
        scrape_interval: 15s