# This rule is not used by the project federated-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to optimizer.uc.pt resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: federated-operator
    app.kubernetes.io/managed-by: kustomize
  name: federatedoperatorconfig-viewer-role
rules:
- apiGroups:
  - optimizer.uc.pt
  resources:
  - federatedoperatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - optimizer.uc.pt
  resources:
  - federatedoperatorconfigs/status
  verbs:
  - get
