---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimizer.uc.pt
  resources:
  - federatedclusters
  - federatedoperatorconfigs
  - federatedplacements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimizer.uc.pt
  resources:
  - federatedclusters/finalizers
  - federatedoperatorconfigs/finalizers
  - federatedplacements/finalizers
  verbs:
  - update
- apiGroups:
  - optimizer.uc.pt
  resources:
  - federatedclusters/status
  - federatedoperatorconfigs/status
  - federatedplacements/status
  verbs:
  - get
  - patch
  - update
