apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: federated-workloads
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
      # Sidecar container para gerar a atividade metabólica normal de um microsserviço
      - name: normal-load-simulator
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        # Executa uma operação de hash a cada 1.5 segundos para simular transações basais
        args:
        - |
          while true; do
            head -c 20m /dev/urandom | md5sum > /dev/null
            sleep 1.5
          done
        resources:
          requests:
            cpu: "50m"