apiVersion: optimizer.uc.pt/v1
kind: FederatedPlacement
metadata:
  labels:
    app.kubernetes.io/name: federated-operator
    app.kubernetes.io/managed-by: kustomize
  name: federatedplacement
  namespace: federated-workloads
spec:
  # targetWorkload: Name of the existing Deployment in the CMC (Approach A)
  targetWorkload: "nginx-deployment"

  # autoScaling: Parameters to manage the lifecycle of the native HPA
  autoScaling:
    minReplicas: 10
    maxReplicas: 10
    targetCPUUtilization: 75
  
  # latencyZones (hij): Traffic fraction targets per geographic zone
  latencyZones:
    Pinhel: "0.5"
    Coimbra: "0.5"
