apiVersion: optimizer.uc.pt/v1
kind: FederatedOperatorConfig
metadata:
  labels:
    app.kubernetes.io/name: federated-operator
    app.kubernetes.io/managed-by: kustomize
  name: global-config
  namespace: federation-system

spec:
  # totalBudget (B): The maximum financial limit for all federated workloads
  totalBudget: "0.06"
  
  # optimizationWeight (alpha): Balance between cost (1) and latency (0)
  optimizationWeight: "0.1"

  # Baseline cost and latency estimates for new clusters
  defaultEstimates:
    cpu: "100m"  
    memory: "3384Ki"

  # normalizationConstant (k): Scale used to normalize latency against cost
  normalizationConstant: "0.001"
