apiVersion: optimizer.uc.pt/v1
kind: FederatedOperatorConfig
metadata:
  labels:
    app.kubernetes.io/name: federated-operator
    app.kubernetes.io/managed-by: kustomize
  name: federatedoperatorconfig-sample
spec:
  # totalBudget (B): The maximum financial limit for all federated workloads
  totalBudget: "1000.00"
  
  # optimizationWeight (alpha): Balance between cost (1) and latency (0)
  optimizationWeight: "0.5"
  
  # normalizationConstant (k): Scale used to normalize latency against cost
  normalizationConstant: "1"
