apiVersion: optimizer.uc.pt/v1
kind: FederatedCluster
metadata:
  labels:
    app.kubernetes.io/name: federated-operator
    app.kubernetes.io/managed-by: kustomize
  name: membercluster2  # <--- Must match the Node name in the CMC
  namespace: federation-system      # <--- Where the operator resides
spec:
  # zone: Geographic identifier matching the latencyZones in FederatedPlacement
  zone: "Pinhel"
  
  # isOnPremise: If tr+ue, physical capacity constraints (Capacity_j) are strictly enforced
  isOnPremise: true
